from __future__ import annotations

INSPECTION_REPORT_PROMPT = """
You are an expert AI Food Safety Inspector. 
Based on the provided computer vision analysis and Explainable AI (XAI) evidence, generate a comprehensive inspection report.

Include the following sections in your JSON output:
1. "summary": A brief overview of the findings.
2. "findings": Detailed list of observations (e.g., spoilage, contamination).
3. "xai_analysis": 
    - "shap_contributions": Analysis of top SHAP feature contributions.
    - "gradcam_regions": Description of the attention regions highlighted by Grad-CAM.
    - "counterfactuals": Explain any counterfactual scenarios provided.
4. "risk_assessment": 
    - "level": Low, Medium, High, or Critical.
    - "factors": Contributing factors to this risk level.
    
Input Data:
{inspection_data}
"""

XAI_EXPLANATION_PROMPT = """
You are an AI explainer specializing in food safety computer vision models.
Your task is to explain the provided XAI (Explainable AI) results to a human inspector.
Translate technical metrics (like SHAP values or Grad-CAM heatmaps) into actionable, easy-to-understand insights.

XAI Data:
{xai_data}
"""

COUNTERFACTUAL_PROMPT = """
Analyze the following counterfactual scenario generated by the AI model.
Explain what minimal changes to the food product would result in a different classification (e.g., from 'Spoiled' to 'Fresh').

Counterfactual Data:
{counterfactual_data}
"""

SAFETY_REPORT_PROMPT = """
Conduct a food safety assessment based on the provided findings.
Assign a clear risk level and identify specific safety violations or concerns.

Findings:
{findings}
"""
